app:
  http:
    server:
      host: 0.0.0.0
      port: 8000

  postgres:
    host: postgres-database
    port: 5432
    database: car_catalog

  api:
    car:
      http:
        client:
          host: https://example.api.car/info
          timeout: 3s